### ISSUE TITLE
Problem with config file waldo file and port

### ISSUE THREAD

**Issue by ghost** [beave/meer#10]
Hi
Compiled under debian stretch
when run the following error occurs.
 Configuration incomplete.  No 'waldo-file' specified!
despite having the following in the config file
 waldo_file: "/var/log/meer/meer.waldo"      # Where to store the last
                                                # position in the
                                                # "follow-eve" file.

Also in the database section of the config file, port is there twice.

**Comment by ghost** [comment]
Hi
in config-yaml,c
else if ( !strcmp(last_pass, "waldo-file" ) || !strcmp(last_pass, "waldo-file" ) )

in etc/meer.config
waldo_file: "/var/log/meer/meer.waldo"

changing to 
waldo-file: "/var/log/meer/meer.waldo"

passes ok.

**Comment by beave** [comment]
First off,  thanks for reporting it.  

I've pushed a patch to fix this.  Please let me know if you have any other issues!
