### ISSUE TITLE
Problema em config-yaml.c 

### ISSUE THREAD

**Issue by viniropke99** [beave/meer#13]
Estou com este problema, já compilei especificando as bibliotecas e nada.  O que poderia ser?
#meer
[E] [04/06/2020 19:53:54] [config-yaml.c, line 189] libyam parse error at line 273 in '/usr/local/etc/meer.yaml'

**Comment by beave** [comment]
Sorry.  Not sure what this means.   I would need to see the yaml file.

**Comment by viniropke99** [comment]
Tem um caractere invisível, seu arquivo não é mais.yaml disponível no código fonte, é necessário remover.

Está na linha 273:
"
Tem um caractere invisível, seu arquivo não é mais.yaml disponível no código fonte, é necessário remover.

Está na linha 273:
"#" list "(" lpush ")," rpush "," channel "(" publish ")""
